export const COUNTRIES = [
  "Argentina",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Denmark",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Kenya",
  "Malaysia",
  "Mexico",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Philippines",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam"
];
export const ISD_CODES = {
  "Argentina": "+54",
  "Australia": "+61",
  "Austria": "+43",
  "Bangladesh": "+880",
  "Belgium": "+32",
  "Brazil": "+55",
  "Canada": "+1",
  "Chile": "+56",
  "China": "+86",
  "Colombia": "+57",
  "Denmark": "+45",
  "Egypt": "+20",
  "Finland": "+358",
  "France": "+33",
  "Germany": "+49",
  "India": "+91",
  "Indonesia": "+62",
  "Ireland": "+353",
  "Israel": "+972",
  "Italy": "+39",
  "Japan": "+81",
  "Kenya": "+254",
  "Malaysia": "+60",
  "Mexico": "+52",
  "Nepal": "+977",
  "Netherlands": "+31",
  "New Zealand": "+64",
  "Nigeria": "+234",
  "Norway": "+47",
  "Pakistan": "+92",
  "Philippines": "+63",
  "Russia": "+7",
  "Saudi Arabia": "+966",
  "Singapore": "+65",
  "South Africa": "+27",
  "South Korea": "+82",
  "Spain": "+34",
  "Sri Lanka": "+94",
  "Sweden": "+46",
  "Switzerland": "+41",
  "Thailand": "+66",
  "Turkey": "+90",
  "United Arab Emirates": "+971",
  "United Kingdom": "+44",
  "United States": "+1",
  "Vietnam": "+84"
};